<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                <div class="control">
                    <div class="quantity-adder">
                    <input type="number" name="qty" id="qty" maxlength="12" value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty  pull-left" data-validate="{'required-number':true,digits:true}"/>
                    <div class="quantity-wrapper pull-left">
                        <span class="add-up add-action fa fa-plus" data-parentqty="true"></span>  
                        <span class="add-down add-action fa fa-minus" data-parentqty="true"></span>
                    </div>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
                <script type="text/javascript">
                            require(["jquery"], function(){
                                jQuery(window).ready( function(){
                                   jQuery(".quantity-adder .add-action").click( function(){
                                    if( jQuery(this).hasClass('add-up') ) {  
                                        jQuery(".quantity-adder .qty").val( parseInt(jQuery(".quantity-adder .qty").val()) + 1 );
                                    }else {
                                        if( parseInt(jQuery(".quantity-adder .qty").val())  > 1 ) {
                                            jQuery(".quantity-adder .qty").val( parseInt(jQuery(".quantity-adder .qty").val()) - 1 );
                                        }
                                    }
                                } );
                               })
                            });
                        </script>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
