<?php
$custom_url = $this->getConfig("custom_url", "");
if ($width): ?>
	<div class="ves-widget widget-google-button block <?php echo $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
		<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
		<div class="block-title">
			<strong><span><?php echo $widget_heading; ?></span></strong>
		</div>
		<?php endif; ?>
		<div class="widget-inner block-content">
			<div class="g-plusone" data-size="<?php echo $size; ?>" data-annotation="<?php echo $annotation; ?>" data-width="<?php echo $width; ?>" <?php echo $custom_url?'data-href="'.$custom_url.'"':'';?>></div>
		</div>
	</div>

<script type="text/javascript">
  window.___gcfg = {lang: 'en-US'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
<?php endif; ?>